---
- name: install fail2ban
  apt: pkg=fail2ban state=installed update_cache=true
  notify:
    - start fail2ban
    - enable fail2ban

- name: create fail2ban jail.local
  template: src="fail2ban/jail-local.j2" dest="/etc/fail2ban/jail.local" owner=root group=root mode=0644
  notify:
    - restart fail2ban
